anguage: java
sudo: false #faster builds

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

cache:
  directories:
    - $HOME/.m2
