anguage: java
sudo: false #faster builds

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

cache:
  directories:
    - $HOME/.m2

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 92b624c5-8dab-4788-8c84-451872a49e1a