version: '3'
services:

  app:
    build: .
    container_name: app
    depends_on:
      - postgis
    ports:
      - "8080:8080"
    environment:
      - postgres.host=postgis

  postgis:
    image: "mdillon/postgis:10"
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

