logging.level.root: info

management.endpoints.web.exposure.include: health,info,metrics

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  pass: "postgres"
  dbname: "postgres"

graphite:
  enabled: false
  prefix: "coding_challenge.dev"
  host: "localhost"
  port: 2003
  refreshPeriodInSeconds: 10
